---
name: 'hostwithquantum/setup-runway'
description: 'Setup the runway CLI on GitHub Actions'
branding:
  icon: 'zap'
  color: 'yellow'
inputs:
  username:
    required: true
    description: runway account
  password:
    required: true
    description: runway password
  public-key-location:
    description: ssh public key location
    required: true
    default: "~/.ssh/id_rsa.pub"
  private-key-location:
    description: ssh private key location
    required: true
    default: "~/.ssh/id_rsa"
  add-key:
    description: if set to true, run "runway key create"
    required: true
    default: 'false'
  setup-ssh:
    description: if set to true, setup ssh to work for "runway app deploy"
    default: 'false'
  log-level:
    description: debug, info, warn, error
    default: error
    required: true
  version:
    description: runway cli version
    default: "latest"
    required: true
  controller-url:
    description: Custom controller URL (for testing + enterprise)
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ARCH=$(uname -m)
        case $ARCH in
          x86_64) ARCH="amd64" ;;
          aarch64) ARCH="arm64" ;;
        esac
        echo "RUNWAY_ARCH=$ARCH" >> $GITHUB_ENV
    - name: install runway cli
      run: |
        curl \
          -H 'Cache-Control: no-cache' \
          "https://download.runway.horse/runway/${{ inputs.version }}/runway_linux_${RUNWAY_ARCH}?nocache=$(date +%s)" \
          -o ${{ github.action_path }}/runway \
          && chmod +x ${{ github.action_path }}/runway
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: "Configure how Runway behaves"
      run: |
        echo "RUNWAY_NONINTERACTIVE=true" >> $GITHUB_ENV
        echo "RUNWAY_LOGLEVEL=${{ inputs.log-level }}" >> $GITHUB_ENV
        echo "RUNWAY_OUTPUT=quiet" >> $GITHUB_ENV
      shell: bash
    - shell: bash
      run: |
        runway -v
        echo "Installed Runway CLI ✅" >> $GITHUB_STEP_SUMMARY
    - shell: bash
      run: |
        runway login -u "${{ inputs.username }}" -p "${{ inputs.password }}"
        echo "Logged in successfully ✅" >> $GITHUB_STEP_SUMMARY
    - run: |
        runway key create ${{ inputs.public-key-location }}
        echo "Imported a new key ✅" >> $GITHUB_STEP_SUMMARY
      if: ${{ inputs.add-key == 'true' }}
      shell: bash
    - run: |
        echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
        ssh-keyscan -p 2222 deploy.runway.horse >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add ${{ inputs.private-key-location }}
      if: ${{ inputs.setup-ssh == 'true' }}
      shell: bash
    - run: echo "RUNWAY_CONTROLLER=${{ inputs.controller-url }}" >> $GITHUB_ENV
      if: ${{ inputs.controller-url != '' }}
      shell: bash
    - shell: bash
      run: |
        echo "Let's deploy something?! 🚀🤘" >> $GITHUB_STEP_SUMMARY
